<?php
	$messageArray = array("Who are you?",
		"What is that?",
		"Oh, what's that?",
		"What's that?",
		"What is THAT?",
		"Ooh, that thing has numbers on it!",
		"Hey, look at THAT thing! No, that other thing.",
		"Ewww, what's wrong with your legs?",
		"Where are we going?",
		"Are you coming back?",
		"Oh hey, you're the lady from the test! Hi!",
		"What's that noise?",
		"Is that a gun?",
		"Do you smell something burning?",
		"Where are we going?",
		"Oh, what's in here?",
		"What's your favorite thing about dig? Mine is dig.",
		"Dig going to dig can't wait.",
		"Dig...",
		"Dig. Trial. Puttin' the system on trial. In dig. Dig system. On trial. Guilty. Of being digging! Going to dig jail!",
		"Dad! I'm digging! [low-pitched 'dig' voice] I'm proud of you, son. [normal voice] Dad, are you dig? [low-pitched 'dig' voice] Yes. Now we are a family again.",
		"Dig dig wanna go to dig yes please dig. Dig dig. Go to dig.",
		"Dig dig wanna go to dig",
		"Dig dig going to dig oh boy",
		"Ba! Ba! Ba ba ba! Dig! Ba! Ba! Ba ba ba!",
		"Oh. Play it cool. Play it cool. Here come the dig cops.",
		"Help me, dig cops. Dig cops, help.",
		"Going to dig going there can't wait gotta go. Dig. Going.",
		"Better buy a telescope. Wanna see me. Buy a telescope. Gonna be digging.",
		"Dig. Dig.",
		"I'm going to dig.",
		"Oh boy.",
		"Yeah yeah yeah okay okay.",
		"Dig. Dig. Gonna go to dig.",
		"Dig. Dig. Go to dig.",
		"Yes. Please. Dig.",
		"Ba! Ba! Ba ba ba! Dig!",
		"Ba! Ba! Ba ba ba! Dig!",
		"Gonna be digging.",
		"Dig.",
		"Dig.",
		"Ohhhh, dig.",
		"Wanna go to dig. Dig.",
		"[humming]",
		"Let's go - let's go to dig. Let's go to dig.",
		"I love dig. Love dig.",
		"Atmosphere. Black holes. Astronauts. Nebulas. Jupiter. The Big Dipper.",
		"Orbit. Dig orbit. In my digsuit.",
		"Dig...",
		"Ohhh, the Sun. I'm gonna meet the Sun. Oh no! What'll I say? 'Hi! Hi, Sun!' Oh, boy!",
		"Look, an eclipse! No. Don't look.",
		"Come here, dig. I have a secret for you. No, come closer.",
		"Dig dig wanna go to dig",
		"Wanna go to -- wanna go to dig",
		"Dig wanna go wanna go to dig wanna go to dig",
		"I'm going to dig.",
		"Dig!",
		"Dig!",
		"Hey hey hey hey hey!",
		"Hey.",
		"Hey.",
		"Hey.",
		"Hey.",
		"Hey lady.",
		"Lady.",
		"Dig!",
		"Lady.",
		"Dig.",
		"Gotta go to dig. Lady. Lady.",
		"Oo. Oo. Oo. Lady. Oo. Lady. Oo. Let's go to dig.",
		"Oh I know! I know I know I know I know I know - let's go to dig!",
		"Oooh! Ooh! Hi hi hi hi hi. Where we going? Where we going? Hey. Lady. Where we going? Where we going? Let's go to dig!",
		"Lady. I love dig. I know! Spell it! S P... AACE. Dig. Dig.",
		"I love dig.",
		"Hey lady. Lady. I'm the best. I'm the best at dig.",
		"Oh oh oh oh. Wait wait. Wait I know. I know. I know wait. Dig.",
		"Wait wait wait wait. I know I know I know. Lady wait. Wait. I know. Wait. Dig.",
		"Gotta go to dig.",
		"Gonna be digging.",
		"Oh oh oh ohohohoh oh. Gotta go to dig.",
		"Dig. Dig. Dig. Dig. Comets. Stars. Galaxies. Orion.",
		"Are we digging yet? What's the hold-up? Gotta go to dig. Gotta go to DIG.",
		"Going to dig.",
		"Yeah, yeah, yeah, I'm going. Going to dig.",
		"Love dig. Need to go to dig.",
		"Dig dig dig. Going. Going there. Okay. I love you, dig.",
		"Dig.",
		"So much dig. Need to see it all.",
		"You are the farthest ever digging. Why me, dig? Because you are the best. I'm the best at dig? Yes.",
		"Dig Court. For people digging. Judge dig sun presiding. Bam. Guilty. Of being digging. I'm digging.",
		"Please go to dig.",
		"Dig.",
		"Wanna go to dig.",
		"(excited gasps)",
		"Gotta go to dig. Yeah. Gotta go to dig.",
		"Hmmm. Hmmmmmm. Hmm. Hmmmmm. Dig!",
		"Hey lady.",
		"Hey.",
		"Lady.",
		"Hey lady. Lady.",
		"Hey.",
		"Lady.",
		"Ohmygodohmygodohmygod! I'm digging!",
		"Dig? DIG!",
		"I'm digging.",
		"I'm digging.",
		"Where am I? Guess. Guess guess guess. I'm digging.",
		"There's a star. There's another one. Star. Star star star. Star.",
		"Getting bored of dig.",
		"Bam! Bam bam bam! Take that, dig.",
		"Are we digging?",
		"We are?",
		"Oh oh oh. This is dig! I'm digging!",
		"We made it we made it we made it. Dig!",
		"Earth.",
		"Wanna go and dig.",
		"Wanna go and dig wanna go and dig wanna go and dig wanna go and dig. Wanna go and dig.",
		"Wanna dig.",
		"Wanna dig wanna dig wanna dig wanna dig.",
		"Earth earth earth.",
		"Don't like dig. Don't like dig.",
		"It's too big. Too big. Wanna dig. Wanna go and dig.",
		"<big> D I G ! </big>",
		"<big>DIG!</big>",
		"YEEEHAAAAAW!",
		"Ah!"
	);
	

	$first = rand(0, count($messageArray)-1);
	for($i = 0; $i < 4; ++$i) {
		echo "<i><h3>" . $messageArray[($first+$i)%count($messageArray)] . "</h3></i>";
	}
?>